### ISSUE TITLE
Lv.1 페어

### ISSUE THREAD

**Issue by 2kyuhang** [ironprayer/post-backend#1]
수정, 삭제 API의 request를 어떤 방식으로 사용하셨나요? (param, query, body)
수정 : @PutMapping("/post/{id}") => @RequestBody PostRequestDTO postRequestDTO, @PathVariable Long id
삭제 : @DeleteMapping("/post/{id}") => @DeleteMapping("/post/{id}")

어떤 상황에 어떤 방식의 request를 써야하나요?
id값은 구분을 위해 @PathVariable / 그 외에는 @RequestBody를 통해 바디 안에 넣어서 데이터를 받아왔습니다.

RESTful한 API를 설계했나요? 어떤 부분이 그런가요? 어떤 부분이 그렇지 않나요?
네 매우 적합하게 사용하셨습니다.

적절한 관심사 분리를 적용하였나요? (Controller, Repository, Service)
네

API 명세서 작성 가이드라인을 검색하여 직접 작성한 API 명세서와 비교해보세요!
동일!

**Comment by ironprayer** [comment]
네 감사합니다.
